const styles = {
  container: {
    padding: "24px 20px",
    maxWidth: 860,
    margin: "0 auto",
  },
  pageCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    padding: 20,
  },
  card: {
    background: "#fff",
    padding: 40,
    borderRadius: 8,
    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
    width: "100%",
    maxWidth: 400,
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 6,
  },
  subtitle: {
    color: "#666",
    marginBottom: 24,
    fontSize: 14,
  },
  input: {
    display: "block",
    width: "100%",
    padding: "10px 12px",
    marginBottom: 12,
    border: "1px solid #ccc",
    borderRadius: 4,
    fontSize: 14,
    outline: "none",
  },
  button: {
    padding: "10px 20px",
    background: "#111",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    width: "100%",
  },
  buttonOutline: {
    padding: "8px 16px",
    background: "transparent",
    color: "#111",
    border: "1px solid #111",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
    flexWrap: "wrap",
    gap: 8,
  },
  userBadge: {
    fontSize: 13,
    color: "#555",
    background: "#eee",
    padding: "4px 10px",
    borderRadius: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 12,
  },
  section: {
    marginBottom: 32,
  },
  muted: {
    color: "#888",
    fontSize: 14,
  },
  alertCard: {
    padding: "12px 14px",
    background: "#fff",
    borderLeft: "4px solid #e74c3c",
    borderRadius: 4,
    marginBottom: 10,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  recCard: {
    display: "flex",
    alignItems: "flex-start",
    padding: "12px 14px",
    background: "#fff",
    border: "1px solid #e0e0e0",
    borderRadius: 4,
    marginBottom: 10,
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  badge: {
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: 20,
  },
  toggleRow: {
    display: "flex",
    gap: 8,
    marginBottom: 14,
  },
  toggleActive: {
    padding: "8px 16px",
    background: "#111",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  toggleInactive: {
    padding: "8px 16px",
    background: "#fff",
    color: "#111",
    border: "1px solid #ccc",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  error: {
    color: "#c0392b",
    fontSize: 13,
    marginBottom: 10,
  },
  tableWrapper: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  },
  th: {
    textAlign: "left",
    padding: "8px 10px",
    background: "#f0f0f0",
    borderBottom: "2px solid #ddd",
    fontWeight: 600,
  },
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid #eee",
    verticalAlign: "middle",
  },
  progressBar: {
    height: 6,
    background: "#e0e0e0",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 2,
    width: 80,
  },
  progressFill: {
    height: "100%",
    background: "#2ecc71",
    borderRadius: 3,
    transition: "width 0.3s",
  },
};

export default styles;
